import Header from "@/components/layout/Header";
import "./globals.css"
import config from "@/config/config";
import { Provider } from "react-redux";
import { store } from "@/redux/store";


export const metadata = {
  title: config.appName,
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <Provider store={store}>
        <Header/>
          {children}
        </Provider>

      </body>
    </html>
  );
}
