import Header from "@/components/layout/Header";
import "./globals.css"
import config from "@/config/config";
import MainProvider from "@/redux/MainProvider";


export const metadata = {
  title: config.appName,
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <MainProvider>
        <Header/>
          {children}
        </MainProvider>

      </body>
    </html>
  );
}
